:concurrency: 5  
:queues:
  - [critical, 3]  
  - [default, 2]   
  - [low, 1]      

:timeout: 30     

:development:
  :concurrency: 3
  :queues:
    - [default, 1]

:production:
  :concurrency: 10
  :queues:
    - [critical, 3]
    - [default, 2]
    - [low, 1]

:redis:
  url: redis://localhost:6379/1